
  categories-db:
    image: postgres:16
    container_name: categories-db
    ports:
      - "5432"
    environment:
      POSTGRES_USER: superman
      POSTGRES_PASSWORD: superman
      POSTGRES_DB: categories_database
    volumes:
      - ../../../rest-categories/deploy/db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/1-init-tables.sql
