
  rest-categories-native:
    image: quay.io/quarkus-magazenn/rest-categories:native-latest
    container_name: rest-categories-native
    depends_on:
      - categories-db
    ports:
      - "8083:8083"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://categories-db:5432/categories_database
      QUARKUS_HIBERNATE_ORM_SCHEMA_MANAGEMENT_STRATEGY: validate
      QUARKUS_DATASOURCE_USERNAME: magazenn
      QUARKUS_DATASOURCE_PASSWORD: arpad5
      QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT: no-file
      QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4317
    restart: on-failure
    networks:
      default:
        aliases:
          - rest-categories
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
